# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
